name: SpawnPoint
author: Nick Lersberghe - Lazoh - MyNameIsLego
version: 1.0
main: main.Main
description: Plugin that allows a player to see where the world's spawn point is located and teleport to that point. The spawn point can be set by operators using the built-in server command /setworldspawn
commands:
    getspawn:
        usage: /<command>
        description: Shows the location of the world spawn
    spawn:
        usage: /<command>
        description: Teleports to the world spawn
    
